config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :promotions do
    member do
      post 'generate_coupons'
      post 'approve'
    end
    get 'search', on: :collection
  end
  resources :coupons, only: [] do
    post 'disable', on: :member
  end

  namespace :api, constraints: ->(req) { req.format == :json } do
    namespace :v1 do
      resources :coupons, only: [:show], param: :code
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coupon.rb
# frozen_string_literal: true

class Coupon < ApplicationRecord
  belongs_to :promotion

  enum status: { active: 0, disabled: 10 }
  delegate :discount_rate, to: :promotion

  def as_json(options = {})
    super({ methods: :discount_rate }.merge(options))
  end
end

app/models/promotion.rb
# frozen_string_literal: true

class Promotion < ApplicationRecord
  belongs_to :user
  has_many :coupons, dependent: :restrict_with_error
  has_one :promotion_approval
  has_one :approver, through: :promotion_approval, source: :user

  validates :name, :code, :discount_rate, :coupon_quantity,
            :expiration_date, presence: true
  validates :code, :name, uniqueness: true
  SEARCHABLE_FIELDS = %w[name code description].freeze

  def generate_coupons!
    return if coupons?

    (1..coupon_quantity).each do |number|
      coupons.create!(code: "#{code}-#{'%04d' % number}")
    end
  end

  # TODO: fazer testes pra esse método
  def coupons?
    coupons.any?
  end

  scope :search, lambda { |query|
    where(
      SEARCHABLE_FIELDS
        .map { |field| "#{field} LIKE :query" }
        .join(' OR '),
      query: "%#{query}%"
    )
      .limit(5)
  }

  scope :available, -> { where('expiration_date >= ?', Time.zone.now) }

  def self.search(query)
    where(
      SEARCHABLE_FIELDS
        .map { |field| "#{field} LIKE :query" }
        .join(' OR '),
      query: "%#{query}%"
    )
      .limit(5)
  end

  def approved?
    promotion_approval.present?
  end

  def can_approve?(current_user)
    user != current_user
  end
end

app/models/promotion_approval.rb
# frozen_string_literal: true

class PromotionApproval < ApplicationRecord
  belongs_to :promotion
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :promotions, dependent: :destroy
  has_many :promotion_approvals, dependent: :nullify
  has_many :approved_promotions, through: :promotion_approvals, source: :promotion
end

app/controllers/api/v1/api_controller.rb
# frozen_string_literal: true

class Api::V1::ApiController < ActionController::API
  respond_to :json

  rescue_from ActiveRecord::RecordNotFound, with: :not_found_error

  private

  def not_found_error
    head 404
  end
end

app/controllers/api/v1/coupons_controller.rb
# frozen_string_literal: true

class Api::V1::CouponsController < Api::V1::ApiController
  def show
    @coupon = Coupon.active.find_by!(code: params[:code])
    # render json: @coupon.as_json(methods: :discount_rate)
    # rescue ActiveRecord::RecordNotFound
    #   head 404
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/coupons_controller.rb
# frozen_string_literal: true

class CouponsController < ApplicationController
  def disable
    @coupon = Coupon.find(params[:id])
    @coupon.disabled!
    redirect_to @coupon.promotion, notice: t('.success', code: @coupon.code)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/promotions_controller.rb
# frozen_string_literal: true

class PromotionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_promotion, only: %i[show edit update destroy
                                         generate_coupons approve]
  before_action :can_be_approved, only: [:approve]

  def index
    @promotions = Promotion.all
  end

  def show; end

  def new
    @promotion = Promotion.new
  end

  def create
    @promotion = current_user.promotions.new(promotion_params)
    if @promotion.save
      redirect_to @promotion
    else
      render :new
    end
  end

  def generate_coupons
    @promotion.generate_coupons!
    redirect_to @promotion, notice: t('.success')
  end

  def edit; end

  def update
    return redirect_to @promotion if @promotion.update(promotion_params)

    render :edit
  end

  def destroy
    if @promotion.destroy
      redirect_to promotions_path, notice: t('.success')
    else
      redirect_to @promotion, notice: t('.failed')
    end
  end

  def search
    @term = params[:q]
    @promotions = Promotion.search(@term)
    render json: @promotions
  end

  def approve
    current_user.promotion_approvals.create!(promotion: @promotion)
    PromotionMailer
      .with(promotion: @promotion, approver: current_user)
      .approval_email
      .deliver_now
    redirect_to @promotion, notice: 'Promoção aprovada com sucesso'
  end

  private

  def set_promotion
    @promotion = Promotion.find(params[:id])
  end

  def promotion_params
    params
      .require(:promotion)
      .permit(:name, :expiration_date, :description,
              :discount_rate, :code, :coupon_quantity)
  end

  def can_be_approved
    return if @promotion.can_approve?(current_user)

    redirect_to @promotion, alert: 'Ação não permitida'
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Promotion System</h1>
<h3>Boas vindas ao sistema de gestão de promoções</h3>

<button type="button" class="btn btn-secondary" data-bs-toggle="tooltip" data-bs-placement="top" title="Tooltip on top">
  Tooltip on top
</button>
<button type="button" class="btn btn-secondary" data-bs-toggle="tooltip" data-bs-placement="right" title="Tooltip on right">
  Tooltip on right
</button>
<button type="button" class="btn btn-secondary" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Tooltip on bottom">
  Tooltip on bottom
</button>
<button type="button" class="btn btn-secondary" data-bs-toggle="tooltip" data-bs-placement="left" title="Tooltip on left">
  Tooltip on left
</button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sistema de Promoções</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="<%= root_path %>">Promotion System</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <% if user_signed_in? %>
            <%= current_user.email %>
            <li class="nav-item">
              <%= link_to 'Sair', destroy_user_session_path, class: 'nav-link', method: :delete %>
            </li>
            <li class="nav-item">
              <%= link_to 'Promoções', promotions_path, class: 'nav-link' %>
            </li>
          <% else %>
            <%= link_to 'Cadastrar', new_user_registration_path %>
            <%= link_to 'Entrar', new_user_session_path %>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="container">
      <% if flash[:notice] %>
        <div class="alert alert-info" role="alert"> 
          <%= flash[:notice] %>
        </div>
      <% end %>
      <p><%= flash[:alert] %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/promotions/_form.html.erb
<%= form_with model: promotion do |f| %>
  <%= render partial: 'shared/form_errors', locals: { object: promotion } %>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.label :code %>
    <%= f.text_field :code %>
  </div>
  <div>
    <%= f.label :discount_rate %>
    <%= f.number_field :discount_rate, in: 0..100, step: 0.1 %>
  </div>
  <div>
    <%= f.label :coupon_quantity %>
    <%= f.number_field :coupon_quantity, min: 1 %>
  </div>
  <div>
    <%= f.label :expiration_date %>
    <%= f.text_field :expiration_date %>
  </div>
  <%= f.submit %>
<% end %>

app/views/promotions/_promotion.html.erb
<h3><%= link_to promotion.name, promotion %></h3>
<dl>
  <dt><%= Promotion.human_attribute_name(:description) %></dt>
  <dd><%= promotion.description %></dd>
  <dt><%= Promotion.human_attribute_name(:discount_rate) %></dt>
  <dd><%= number_to_percentage promotion.discount_rate, separator: ',', precision: 2 %></dd>
</dl>

app/views/promotions/edit.html.erb
<h1>Atualizar uma promoção</h1>

<%= render partial: 'form', locals: { promotion: @promotion } %>

app/views/promotions/index.html.erb
<%= link_to 'Voltar', root_path %>

<%= link_to 'Registrar uma promoção', new_promotion_path, class: 'btn btn-success' %>

<%= form_with url: search_promotions_path, id: 'search-promotion', method: :get, local: false do |f| %>
  <%= f.label :q, 'Busca' %>
  <%= f.text_field :q %>
  <%= f.submit 'Buscar' %>
<% end %>

<% if @promotions.empty? %>
  <h3>Nenhuma promoção cadastrada</h3>
<% end %>

<div id="promotions">
  <%= render @promotions %>
</div>

<script>
var searchForm = document.querySelector("#search-promotion")
var promotionDiv = document.querySelector("#promotions")

searchForm.addEventListener("ajax:success", (event) => {
  const [_data, _status, xhr] = event.detail
  const promotions = JSON.parse(xhr.response)
  promotionDiv.innerHTML = ""
  promotions.forEach((promotion) => {
    promotionDiv.insertAdjacentHTML("beforeend", promotion.code)
  })
})
searchForm.addEventListener("ajax:error", (event) => {
  promotionDiv.innerHTML = ""
  promotionDiv.insertAdjacentHTML("beforeend", "<p style='background-color: red; color: green;'>OPA deu erro aqui</p>")
})
</script>

app/views/promotions/new.html.erb
<h1>Registrar uma promoção</h1>

<% if @promotion.errors.any? %>
  <h4>Não foi possível salvar encontramos alguns errors:</h4>
  <ul>
    <% @promotion.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @promotion do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.label :code %>
    <%= f.text_field :code %>
  </div>
  <div>
    <%= f.label :discount_rate %>
    <%= f.number_field :discount_rate, in: 0..100, step: 0.1 %>
  </div>
  <div>
    <%= f.label :coupon_quantity %>
    <%= f.number_field :coupon_quantity, min: 1 %>
  </div>
  <div>
    <%= f.label :expiration_date %>
    <%= f.text_field :expiration_date %>
  </div>
  <%= f.submit %>
<% end %>

app/views/promotions/search.html.erb
<%= link_to 'Voltar', root_path %>

<%= link_to 'Registrar uma promoção', new_promotion_path %>

<%= form_with url: search_promotions_path, method: :get do |f| %>
  <%= f.label :q, 'Busca' %>
  <%= f.text_field :q %>
  <%= f.submit 'Buscar' %>
<% end %>

<%= t '.result', count: @promotions.count, term: @term %>

<%= render @promotions %>

app/views/promotions/show.html.erb
<%= link_to t('buttons.back'), promotions_path %>
<%= link_to t('buttons.edit'), edit_promotion_path(@promotion) %>
<%= link_to t('buttons.destroy'), promotion_path(@promotion), method: :delete, data: { confirm: t('.destroy_confirm') } %>

<h3><%= @promotion.name %></h3>
<dl>
  <dt><%= Promotion.human_attribute_name(:description) %></dt>
  <dd><%= @promotion.description %></dd>
  <dt><%= Promotion.human_attribute_name(:discount_rate) %> <small>em porcentagem</small></dt>
  <dd><%= number_to_percentage @promotion.discount_rate, precision: 2 %></dd>
  <dt>Código</dt>
  <dd><%= @promotion.code %></dd>
  <dt>Data de término</dt>
  <dd><%= l @promotion.expiration_date %></dd>
  <dt>Quantidade de cupons</dt>
  <dd><%= @promotion.coupon_quantity %></dd>
</dl>

<% if @promotion.approved? %>
  <p>Aprovada por: <%= @promotion.approver.email %></p>
  <% if @promotion.coupons.empty? %>
    <%= link_to t('.generate_coupons'), generate_coupons_promotion_path(@promotion), method: :post %>
  <% end %>
<% elsif @promotion.can_approve?(current_user) %>
  <%= link_to 'Aprovar', approve_promotion_path(@promotion), method: :post, data: { confirm: 'Tem certeza? Essa operação não pode ser desfeita' } %>
<% end %>

<% @promotion.coupons.each do |coupon| %>
  <div id="coupon-<%= coupon.code.parameterize %>">
    <p>
      <%= coupon.code %> (<%= Coupon.human_attribute_name("status.#{coupon.status}") %>)
    </p>
    <% if coupon.active? %>
      <%= link_to 'Desabilitar', disable_coupon_path(coupon), method: :post, data: { disable_with: 'Estamos desabilitando....' } %>
    <% end %>
  </div>
<% end %>

app/views/shared/_form_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= t('error_message', count: object.errors.count, model: object.model_name.human.downcase) %></h2>

    <ul>
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>